export interface Member {
  id: string; // UUID generated by client upon join
  displayName: string; // "Alice"
  joinedAt: number; // Date.now()
}

export interface Group {
  id: string; // Unique UUID (Technical ID, Hidden)
  name: string; // "Da Lat Trip" (or auto-generated)
  normalizeName: string; // "da lat trip"
  pin: string; // 6-digit numeric PIN (Shareable ID)
  createdAt: number;
  updatedAt: number;
  currency: string; // Default "VND"
  members: Member[];
}

export interface Expense {
  id: string;
  groupId: string;
  description: string; // "Dinner at Market"
  amount: number; // 500000
  payerId: string; // Reference to Member.id
  payerName: string; // Snapshot of name (for history)
  involvedMemberIds: string[]; // Who is splitting this bill?
  createdAt: number; // Date.now() from server
  createdBy: string; // Member.id of who entered it
  type?: 'expense' | 'reimbursement'; // Defaults to 'expense'
}
