export interface Member {
  id: string; // UUID generated by client upon join
  displayName: string; // "Alice"
  joinedAt: number; // Date.now()
}

export interface Group {
  id: string; // Unique UUID (Technical ID, Hidden)
  name: string; // "Da Lat Trip" (or auto-generated)
  normalizeName: string; // "da lat trip"
  pin: string; // 6-digit numeric PIN (Shareable ID)
  createdAt: number;
  updatedAt: number;
  currency: string; // Default "VND"
  members: Member[];
}
